# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Dataset": "01_data.ipynb",
         "Model": "02_model.ipynb",
         "RecoverMissing": "03_recover_missing.ipynb"}

modules = ["core.py",
           "data.py",
           "model.py",
           "recover_missing.py"]

doc_url = "https://fastai.github.io/task_substitution/"

git_url = "https://github.com/fastai/task_substitution/tree/master/"

def custom_doc_links(name): return None
